### PR TITLE
module: Add EBS extra volume support

### PR DESCRIPTION
**Pull request by jieyu**
Allow extra EBS volumes to be created for each AWS instance.

### CODE REVIEW

**Review by fatz — CHANGES_REQUESTED** [review]
see dcos-terraform/terraform-aws-instance#6

**Comment by fatz** [comment]
please let the module refer to "<~ 0.1.2" instance

**Comment by jieyu** [comment]
@fatz PTAL again. I bump the dependency version

**Review by fatz — APPROVED** [review]

**Comment by fatz** [comment]
overriding CI. Change in already in master no need for merge back

**Pull request merged**
